import { Badge, Member, Participation } from './types';

export const CITIES = [
    'Cape Town',
    'Stellenbosch',
    'Paarl',
    'Somerset West',
    'George',
];

export const BADGES: Badge[] = [
    { id: 'b1', name: 'Volunteer', description: 'Participated in 1 event', icon: 'Hand' },
    { id: 'b2', name: 'Eco-Warrior', description: 'Joined a cleanup', icon: 'Leaf' },
    { id: 'b3', name: 'Learner', description: 'Attended a webinar', icon: 'BookOpen' },
    { id: 'b4', name: 'Connector', description: 'Brought a friend', icon: 'Users' },
    { id: 'b5', name: 'Steward', description: 'Organized an event', icon: 'Star' },
    { id: 'b6', name: 'Guardian', description: 'Reached Guardian status', icon: 'Shield' },
    { id: 'b7', name: 'Local Hero', description: 'Active in your area', icon: 'MapPin' },
    { id: 'b8', name: 'Innovator', description: 'Submitted an idea', icon: 'Lightbulb' },
    { id: 'b9', name: 'Influence', description: 'Shared progress', icon: 'Share2' },
    { id: 'b10', name: 'Legend', description: 'Completed all tiers', icon: 'Award' },
];

export const MOCK_USER_BADGES = ['b1', 'b2', 'b3', 'b4', 'b7', 'b8', 'b9']; // 7 badges

export const MEMBERS: Member[] = [
    { id: 'm1', name: 'Thandiwe N.', tier: 'Guardian', city: 'Cape Town', avatar: 'TN' },
    { id: 'm2', name: 'David K.', tier: 'Steward', city: 'Cape Town', avatar: 'DK' },
    { id: 'm3', name: 'Sarah L.', tier: 'Volunteer', city: 'Stellenbosch', avatar: 'SL' },
    { id: 'm4', name: 'Mike E.', tier: 'GOF', city: 'Cape Town', avatar: 'ME' },
    { id: 'm5', name: 'Jessica R.', tier: 'Guardian', city: 'George', avatar: 'JR' },
];

export const PARTICIPATION_ITEMS: Participation[] = [
    {
        id: 'p1',
        type: 'event',
        title: 'Beach Cleanup: Muizenberg',
        category: 'Local Action',
        mode: 'in_person',
        status: 'open',
        city: 'Cape Town',
        area: 'Muizenberg',
        date: '2026-02-15T09:00:00Z',
        goal: 'Remove 50kg of plastic from the coastline.',
        whyItMatters: 'Plastic pollution harms marine life and microplastics enter our food chain.',
        whatYouDo: ['Meet at Surfer’s Corner', 'Collect bags and gloves', 'Clean the beach for 2 hours', 'Sort waste for recycling'],
        tags: ['Family Friendly', 'Outdoors'],
        badgesAwarded: [BADGES[1]],
    },
    {
        id: 'p2',
        type: 'challenge',
        title: 'Plastic-Free Week',
        category: 'Local Action',
        mode: 'any',
        status: 'open',
        city: 'Cape Town',
        date: '2026-02-01T00:00:00Z',
        goal: 'Avoid single-use plastics for 7 days.',
        whyItMatters: 'Reducing demand for single-use plastic forces manufacturers to change.',
        whatYouDo: ['Refuse straws and bags', 'Use reusable cups', 'Buy loose vegetables', 'Log your success daily'],
        tags: ['Remote', 'Verification required'],
        badgesAwarded: [BADGES[1]],
    },
    {
        id: 'p3',
        type: 'webinar',
        title: 'Urban Farming 101',
        category: 'Learning',
        mode: 'online',
        status: 'open',
        city: 'Cape Town',
        date: '2026-02-10T18:00:00Z',
        goal: 'Learn how to start a food garden in small spaces.',
        whyItMatters: 'Food security starts at home. Local food reduces carbon footprint.',
        whatYouDo: ['Register for Zoom link', 'Prepare questions', 'Join the live session'],
        tags: ['Online', 'Beginner'],
        badgesAwarded: [BADGES[2]],
    },
    {
        id: 'p4',
        type: 'event',
        title: 'Fynbos Restoration Day',
        category: 'Citizen Science',
        mode: 'in_person',
        status: 'closed',
        city: 'Cape Town',
        area: 'Table Mountain',
        date: '2026-01-20T08:00:00Z',
        goal: 'Clear alien vegetation from Plot 4.',
        whyItMatters: 'Alien plants consume excess water and threaten indigenous species.',
        whatYouDo: ['Hike to location', 'Clear Port Jackson willow', 'Stack for chipping'],
        tags: ['Physical', 'Nature'],
        badgesAwarded: [BADGES[1]],
        outcomeSummary: 'We cleared 2 hectares of alien vegetation, saving an estimated 10,000 liters of water per year for the catchment area.',
        outcomeImage: '/images/outcome-1.jpg',
    },
    {
        id: 'p5',
        type: 'challenge',
        title: 'Spot the Leopard Toad',
        category: 'Citizen Science',
        mode: 'in_person',
        status: 'open',
        city: 'Cape Town',
        area: 'Kirstenhof',
        date: '2026-02-20T19:00:00Z',
        goal: 'Log sightings of the endangered Western Leopard Toad.',
        whyItMatters: 'Migration data helps planning safe crossings.',
        whatYouDo: ['Download the app', 'Listen for calls', 'Upload photos and location'],
        tags: ['Night', 'Nature'],
        badgesAwarded: [BADGES[6]],
    },
    {
        id: 'p6',
        type: 'event',
        title: 'Community Kitchen Volunteer',
        category: 'Local Action',
        mode: 'in_person',
        status: 'open',
        city: 'Stellenbosch',
        date: '2026-02-12T10:00:00Z',
        goal: 'Cook 200 meals for the shelter.',
        whyItMatters: 'Nutrition is fundamental to dignity and health.',
        whatYouDo: ['Prep vegetables', 'Cook immense pots', 'Serve meals', 'Clean up'],
        tags: ['Service', 'Community'],
        badgesAwarded: [BADGES[0]],
    },
];
