import { Badge, Member, Participation } from './types';

export const CITIES = [
    'Cape Town',
    'Stellenbosch',
    'Paarl',
    'Somerset West',
    'George',
];

export const BADGES: Badge[] = [
    { id: 'b1', name: 'Volunteer', description: 'Participated in 1 event', icon: 'Hand' },
    { id: 'b2', name: 'Eco-Warrior', description: 'Joined a cleanup', icon: 'Leaf' },
    { id: 'b3', name: 'Learner', description: 'Attended a webinar', icon: 'BookOpen' },
    { id: 'b4', name: 'Connector', description: 'Brought a friend', icon: 'Users' },
    { id: 'b5', name: 'Steward', description: 'Organized an event', icon: 'Star' },
    { id: 'b6', name: 'Guardian', description: 'Reached Guardian status', icon: 'Shield' },
    { id: 'b7', name: 'Local Hero', description: 'Active in your area', icon: 'MapPin' },
    { id: 'b8', name: 'Innovator', description: 'Submitted an idea', icon: 'Lightbulb' },
    { id: 'b9', name: 'Influence', description: 'Shared progress', icon: 'Share2' },
    { id: 'b10', name: 'Legend', description: 'Completed all tiers', icon: 'Award' },
];

export const MOCK_USER_BADGES = ['b1', 'b2', 'b3', 'b4', 'b7', 'b8', 'b9']; // 7 badges

export const MEMBERS: Member[] = [
    { id: 'm1', name: 'Thandiwe N.', tier: 'Guardian', city: 'Cape Town', avatarImage: '/images/ben-den-engelsen-YUu9UAcOKZ4-unsplash.jpg', badgesEarned: 12 },
    { id: 'm2', name: 'David K.', tier: 'Steward', city: 'Cape Town', avatarImage: '/images/ayo-ogunseinde-sibVwORYqs0-unsplash.jpg', badgesEarned: 8 },
    { id: 'm3', name: 'Sarah L.', tier: 'Volunteer', city: 'Stellenbosch', avatarImage: '/images/christopher-campbell-rDEOVtE7vOs-unsplash.jpg', badgesEarned: 3 },
    { id: 'm4', name: 'Mike E.', tier: 'GOF', city: 'Cape Town', avatarImage: '/images/joseph-gonzalez-iFgRcqHznqg-unsplash.jpg', badgesEarned: 25 },
    { id: 'm5', name: 'Jessica R.', tier: 'Guardian', city: 'George', avatarImage: '/images/prince-akachi-J1OScm_uHUQ-unsplash.jpg', badgesEarned: 9 },
];

export const PARTICIPATION_ITEMS: Participation[] = [
    {
        id: 'p1',
        type: 'event',
        title: 'Beach Cleanup: Muizenberg',
        category: 'Local Action',
        mode: 'in_person',
        status: 'open',
        city: 'Cape Town',
        area: 'Muizenberg',
        date: '2026-02-15T09:00:00Z',
        goal: 'Remove 50kg of plastic from the coastline.',
        whyItMatters: 'Plastic pollution harms marine life and microplastics enter our food chain.',
        whatYouDo: ['Meet at Surfer’s Corner', 'Collect bags and gloves', 'Clean the beach for 2 hours', 'Sort waste for recycling'],
        tags: ['Family Friendly', 'Outdoors'],
        badgesAwarded: [BADGES[1]],
        earnedBadgeName: 'Eco-Warrior',
        imageUrl: '/images/Beach Cleanup.jpg',
        joinedMemberIds: ['m1', 'm2', 'm4']
    },
    {
        id: 'p2',
        type: 'event', // Changed from challenge to event
        title: 'Plastic-Free Week',
        category: 'Local Action',
        mode: 'any',
        status: 'open',
        city: 'Cape Town',
        date: '2026-02-01T00:00:00Z',
        goal: 'Avoid single-use plastics for 7 days.',
        whyItMatters: 'Reducing demand for single-use plastic forces manufacturers to change.',
        whatYouDo: ['Refuse straws and bags', 'Use reusable cups', 'Buy loose vegetables', 'Log your success daily'],
        tags: ['Remote', 'Action'],
        badgesAwarded: [BADGES[1]],
        earnedBadgeName: 'Innovator',
        imageUrl: '/images/Plastic free week.jpg',
        joinedMemberIds: ['m3', 'm5']
    },
    {
        id: 'p3',
        type: 'webinar',
        title: 'Urban Farming 101',
        category: 'Learning',
        mode: 'online',
        status: 'open',
        city: 'Cape Town',
        date: '2026-02-10T18:00:00Z',
        platform: 'Google Meets',
        goal: 'Learn how to start a food garden in small spaces.',
        whyItMatters: 'Food security starts at home. Local food reduces carbon footprint.',
        whatYouDo: ['Register for Zoom link', 'Prepare questions', 'Join the live session'],
        tags: ['Online', 'Beginner'],
        badgesAwarded: [BADGES[2]],
        earnedBadgeName: 'Learner',
        imageUrl: '/images/event-learning.jpg',
        joinedMemberIds: ['m1', 'm2', 'm3', 'm4', 'm5']
    },
    {
        id: 'p4',
        type: 'event',
        title: 'Fynbos Restoration Day',
        category: 'Citizen Science',
        mode: 'in_person',
        status: 'closed',
        city: 'Cape Town',
        area: 'Table Mountain',
        date: '2026-01-20T08:00:00Z',
        goal: 'Clear alien vegetation from Plot 4.',
        whyItMatters: 'Alien plants consume excess water and threaten indigenous species.',
        whatYouDo: ['Hike to location', 'Clear Port Jackson willow', 'Stack for chipping'],
        tags: ['Physical', 'Nature'],
        badgesAwarded: [BADGES[1]],
        earnedBadgeName: 'Guardian',
        outcomeSummary: 'We cleared 2 hectares of alien vegetation, saving an estimated 10,000 liters of water per year for the catchment area.',
        outcomeDescription: 'Volunteers gathered early morning to tackle the invasive Port Jackson willow. It was a successful day ensuring the local biodiversity can thrive.',
        outcomeImage: '/images/outcome-1.jpg',
        imageUrl: '/images/event-local-action-2.jpg',
        contributedMemberIds: ['m2', 'm4', 'm1']
    },
    {
        id: 'p5',
        type: 'challenge',
        title: 'Spot the Leopard Toad',
        category: 'Citizen Science',
        mode: 'in_person',
        status: 'open',
        city: 'Cape Town',
        area: 'Kirstenhof',
        date: '2026-02-20T19:00:00Z',
        goal: 'Log sightings of the endangered Western Leopard Toad.',
        whyItMatters: 'Migration data helps planning safe crossings.',
        whatYouDo: ['Download the app', 'Listen for calls', 'Upload photos and location'],
        tags: ['Night', 'Nature', 'Citizen Science'],
        badgesAwarded: [BADGES[6]],
        earnedBadgeName: 'Local Hero',
        researchPartner: 'Western Leopard Toad Conservation Committee',
        imageUrl: '/images/spot the leopard Toad.jpg',
        joinedMemberIds: ['m4', 'm5']
    },
    {
        id: 'p7',
        type: 'challenge',
        title: 'Table Bay Bird Spotting',
        category: 'Citizen Science',
        mode: 'in_person',
        status: 'open',
        city: 'Cape Town',
        area: 'Table Bay',
        date: '2026-03-01T08:00:00Z',
        goal: 'Catalog sea birds along the Table Bay coastline.',
        whyItMatters: 'Bird populations are key indicators of marine ecosystem health.',
        whatYouDo: ['Bring camera or binoculars', 'Identify species', 'Submit counts via app'],
        tags: ['Daytime', 'Coastal', 'Citizen Science'],
        badgesAwarded: [BADGES[2]],
        earnedBadgeName: 'Eco-Warrior',
        researchPartner: 'BirdLife South Africa',
        imageUrl: '/images/Table bay bird spotting.jpg',
        joinedMemberIds: ['m1']
    },
    {
        id: 'p8',
        type: 'challenge',
        title: 'Boulders Beach Penguin Count',
        category: 'Citizen Science',
        mode: 'in_person',
        status: 'open',
        city: 'Cape Town',
        area: 'Boulders Beach',
        date: '2026-03-15T09:00:00Z',
        goal: 'Monitor African Penguin colony numbers during molting season.',
        whyItMatters: 'Accurate population counts are vital for conservation strategies of this endangered species.',
        whatYouDo: ['Observe from boardwalks', 'Count individuals in designated zones', 'Record behavior notes'],
        tags: ['Wildlife', 'Count-based', 'Citizen Science'],
        badgesAwarded: [BADGES[5]],
        earnedBadgeName: 'Guardian',
        researchPartner: 'SANCCOB',
        imageUrl: '/images/Boulders beach penguin count.jpg',
        joinedMemberIds: ['m1', 'm2', 'm3']
    },
    {
        id: 'p6',
        type: 'event',
        title: 'Community Kitchen Volunteer',
        category: 'Local Action',
        mode: 'in_person',
        status: 'open',
        city: 'Stellenbosch',
        date: '2026-02-12T10:00:00Z',
        goal: 'Cook 200 meals for the shelter.',
        whyItMatters: 'Nutrition is fundamental to dignity and health.',
        whatYouDo: ['Prep vegetables', 'Cook immense pots', 'Serve meals', 'Clean up'],
        tags: ['Service', 'Community'],
        badgesAwarded: [BADGES[0]],
        earnedBadgeName: 'Local Hero',
        imageUrl: '/images/Community kitchen volunteer.jpg',
        joinedMemberIds: ['m3']
    },
    // Discover Items (Learning)
    {
        id: 'p9',
        type: 'event',
        title: 'Rewilding Cities: Small Habits, Big Shifts',
        category: 'Learning',
        mode: 'online',
        status: 'open',
        city: 'Cape Town',
        date: '2026-03-05T18:00:00Z',
        platform: 'Zoom',
        goal: 'Understand how small urban gardens support biodiversity.',
        whyItMatters: 'Urban rewilding connects fragmented habitats.',
        whatYouDo: ['Watch the stream', 'Q&A with ecologist'],
        tags: ['Online', 'Learning'],
        badgesAwarded: [BADGES[2]],
        earnedBadgeName: 'Learner',
        imageUrl: '/images/event-learning.jpg',
        joinedMemberIds: ['m1', 'm2', 'm5']
    },
    {
        id: 'p10',
        type: 'event',
        title: 'Cape Town Water Stories: What Our Rivers Teach Us',
        category: 'Learning',
        mode: 'in_person',
        status: 'open',
        city: 'Cape Town',
        area: 'V&A Waterfront',
        date: '2026-03-12T17:30:00Z',
        goal: 'Explore the history and future of Cape Town’s waterways.',
        whyItMatters: 'Water awareness is critical for our future resilience.',
        whatYouDo: ['Attend talk', 'Walk the canal'],
        tags: ['In-person', 'Learning'],
        badgesAwarded: [BADGES[2]],
        earnedBadgeName: 'Learner',
        imageUrl: '/images/Cape Town water stories.jpg',
        joinedMemberIds: ['m4']
    },
    // Closed Outcomes
    {
        id: 'p11',
        type: 'event',
        title: 'Sea Point Promenade Litter Audit',
        category: 'Local Action',
        mode: 'in_person',
        status: 'closed',
        city: 'Cape Town',
        area: 'Sea Point',
        date: '2026-01-15T09:00:00Z',
        goal: 'Audit waste types along the promenade.',
        whyItMatters: 'Data drives policy change on single-use items.',
        whatYouDo: ['Collect litter', 'Categorize brands', 'Weigh and report'],
        whatWasDone: ['Collected litter along 2km of promenade', 'Categorized over 50 brands', 'Weighed 45kg of waste and reported to council'],
        tags: ['Cleanup', 'Data'],
        badgesAwarded: [BADGES[1]],
        earnedBadgeName: 'Steward',
        outcomeSummary: 'We collected 45kg of waste, 60% of which was single-use food packaging. Data submitted to city council.',
        outcomeImage: '/images/outcome-1.jpg',
        imageUrl: '/images/Sea point promenade.jpg',
        contributedMemberIds: ['m1', 'm2', 'm3', 'm4', 'm5']
    },
    {
        id: 'p12',
        type: 'event',
        title: 'Tokai Trail Snare Removal',
        category: 'Local Action',
        mode: 'in_person',
        status: 'closed',
        city: 'Cape Town',
        area: 'Tokai',
        date: '2026-01-08T07:00:00Z',
        goal: 'Remove illegal snares from the greenbelt.',
        whyItMatters: 'Snares indiscriminately trap wildlife and pets.',
        whatYouDo: ['Patrol designated zones', 'Remove hardware', 'Log GPS coords'],
        whatWasDone: ['Patrolled 3 designated zones', 'Removed 12 illegal snares', 'Logged GPS coordinates for future monitoring'],
        tags: ['Conservation', 'Active'],
        badgesAwarded: [BADGES[1]],
        earnedBadgeName: 'Guardian',
        outcomeSummary: 'Removed 12 active snares from the upper trail loops, preventing harm to local porcupines and caracals.',
        outcomeImage: '/images/outcome-2.jpg',
        imageUrl: '/images/Tokai Trail.jpg',
        contributedMemberIds: ['m4']
    },
    {
        id: 'p13',
        type: 'challenge',
        title: 'False Bay Kelp Mapping',
        category: 'Citizen Science',
        mode: 'in_person',
        status: 'closed',
        city: 'Cape Town',
        area: 'False Bay',
        date: '2026-01-05T08:00:00Z',
        goal: 'Map kelp forest density via drone imagery analysis.',
        whyItMatters: 'Kelp forests are vital carbon sinks and nurseries for marine life.',
        whatYouDo: ['Analyze drone footage', 'Tag density zones', 'Submit report'],
        whatWasDone: ['Analyzed 5 hours of drone footage', 'Tagged high-density kelp zones', 'Submitted comprehensive report to researchers'],
        tags: ['Remote', 'Data'],
        badgesAwarded: [BADGES[2]],
        earnedBadgeName: 'Learner',
        outcomeSummary: 'Mapped 15km of coastline. Data shows a 10% increase in kelp density compared to 2024.',
        outcomeImage: '/images/outcome-1.jpg', // Reusing
        imageUrl: '/images/event-water.jpg',
        contributedMemberIds: ['m4', 'm1']
    },
    {
        id: 'p14',
        type: 'webinar',
        title: 'Sustainable Seafood Workshop',
        category: 'Learning',
        mode: 'online',
        status: 'closed',
        city: 'Cape Town',
        date: '2025-12-15T18:00:00Z',
        platform: 'Zoom',
        goal: 'Learn how to choose sustainable seafood options.',
        whyItMatters: 'Overfishing threatens global fish stocks.',
        whatYouDo: ['Attend workshop', 'Download SASSI app'],
        whatWasDone: ['Attended 2-hour interactive workshop', 'Downloaded and set up SASSI app', 'Pledged to support sustainable fisheries'],
        tags: ['Online', 'Learning'],
        badgesAwarded: [BADGES[2]],
        earnedBadgeName: 'Connector',
        outcomeSummary: '200 participants pledged to check SASSI list before ordering seafood.',
        outcomeImage: '/images/outcome-1.jpg', // Reusing
        imageUrl: '/images/event-learning.jpg',
        contributedMemberIds: ['m4', 'm2']
    },
];
